### ISSUE TITLE
Droits et notifications

### ISSUE THREAD

**Issue by benel** [UTT-GL03/Blutt#1]
Bonjour @raphaelweis 

N'oubliez pas de définir dans votre entrepôt un rôle pour votre camarade de binôme, de manière à ce qu'il puisse contribuer mais également être notifié lorsque je vous fais des recommandations.

Merci d'avance.

**Comment by raphaelweis** [comment]
Bonjour,
C'est corrigé, j'ai ajouté @medchouai en tant qu'admin.
